name: hassman
version: 0.1.0.0
github: "alenkis/hassman"
license: BSD3
author: "Alen Kis"
maintainer: "alen@alenkis.com"
copyright: "2022 Alen Kis"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/hassman#readme>

dependencies:
  - base >= 4.7 && < 5
  - optparse-applicative
  - persistent
  - persistent-sqlite
  - persistent-template
  - text
  - Hclip
  - pwstore-fast
  - elocrypt
  - random
  - time

library:
  source-dirs: src

executables:
  hassman:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hassman

tests:
  hassman-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hassman
